from torch._dynamo.piper import Task

pp2_interleaved_1f1b_grid_schedule = [
    [
        Task(device_id=0, stage_id=0, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=2, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=2, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=2, mb_idx=0, is_fwd=False, upd=False),
        None,
        Task(device_id=0, stage_id=2, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=2, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=2, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=1, is_fwd=False, upd=False),
        None,
        Task(device_id=0, stage_id=2, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=2, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=0, is_fwd=False, upd=True),
    ],
    [
        None,
        Task(device_id=1, stage_id=1, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=3, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=0, is_fwd=False, upd=True),
        None,
    ],
]

pp4_interleaved_1f1b_grid_schedule = [
    [
        Task(device_id=0, stage_id=0, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=4, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=4, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=4, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=0, stage_id=4, mb_idx=3, is_fwd=True, upd=False),
        None,
        None,
        None,
        Task(device_id=0, stage_id=4, mb_idx=0, is_fwd=False, upd=False),
        None,
        Task(device_id=0, stage_id=4, mb_idx=1, is_fwd=False, upd=False),
        None,
        Task(device_id=0, stage_id=4, mb_idx=2, is_fwd=False, upd=False),
        None,
        Task(device_id=0, stage_id=4, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=0, stage_id=0, mb_idx=0, is_fwd=False, upd=True),
    ],
    [
        None,
        Task(device_id=1, stage_id=1, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=5, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=5, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=5, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=1, stage_id=5, mb_idx=3, is_fwd=True, upd=False),
        None,
        Task(device_id=1, stage_id=5, mb_idx=0, is_fwd=False, upd=False),
        None,
        Task(device_id=1, stage_id=5, mb_idx=1, is_fwd=False, upd=False),
        None,
        Task(device_id=1, stage_id=5, mb_idx=2, is_fwd=False, upd=False),
        None,
        Task(device_id=1, stage_id=5, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=1, stage_id=1, mb_idx=0, is_fwd=False, upd=True),
        None,
    ],
    [
        None,
        None,
        Task(device_id=2, stage_id=2, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=6, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=6, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=6, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=6, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=2, stage_id=6, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=2, stage_id=6, mb_idx=1, is_fwd=False, upd=False),
        None,
        Task(device_id=2, stage_id=6, mb_idx=2, is_fwd=False, upd=False),
        None,
        Task(device_id=2, stage_id=6, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=2, stage_id=2, mb_idx=0, is_fwd=False, upd=True),
        None,
        None,
    ],
    [
        None,
        None,
        None,
        Task(device_id=3, stage_id=3, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=0, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=1, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=2, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=3, is_fwd=True, upd=False),
        Task(device_id=3, stage_id=7, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=0, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=1, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=2, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=3, is_fwd=False, upd=False),
        Task(device_id=3, stage_id=3, mb_idx=0, is_fwd=False, upd=True),
        None,
        None,
        None,
    ],
]